//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PoliceVolunteerUI.WebServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="generalWSSoap", Namespace="http://tempuri.org/")]
    public partial class generalWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetFutureActivitysOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFutureCoursesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddVolunteerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVolunteerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public generalWS() {
            this.Url = global::PoliceVolunteerUI.Properties.Settings.Default.PoliceVolunteerUI_WebServiceReference_generalWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetFutureActivitysCompletedEventHandler GetFutureActivitysCompleted;
        
        /// <remarks/>
        public event GetActivityCompletedEventHandler GetActivityCompleted;
        
        /// <remarks/>
        public event GetFutureCoursesCompletedEventHandler GetFutureCoursesCompleted;
        
        /// <remarks/>
        public event GetCourseCompletedEventHandler GetCourseCompleted;
        
        /// <remarks/>
        public event AddVolunteerCompletedEventHandler AddVolunteerCompleted;
        
        /// <remarks/>
        public event GetVolunteerCompletedEventHandler GetVolunteerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFutureActivitys", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetFutureActivitys() {
            object[] results = this.Invoke("GetFutureActivitys", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetFutureActivitysAsync() {
            this.GetFutureActivitysAsync(null);
        }
        
        /// <remarks/>
        public void GetFutureActivitysAsync(object userState) {
            if ((this.GetFutureActivitysOperationCompleted == null)) {
                this.GetFutureActivitysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFutureActivitysOperationCompleted);
            }
            this.InvokeAsync("GetFutureActivitys", new object[0], this.GetFutureActivitysOperationCompleted, userState);
        }
        
        private void OnGetFutureActivitysOperationCompleted(object arg) {
            if ((this.GetFutureActivitysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFutureActivitysCompleted(this, new GetFutureActivitysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActivity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActivityBL GetActivity(int activityCode) {
            object[] results = this.Invoke("GetActivity", new object[] {
                        activityCode});
            return ((ActivityBL)(results[0]));
        }
        
        /// <remarks/>
        public void GetActivityAsync(int activityCode) {
            this.GetActivityAsync(activityCode, null);
        }
        
        /// <remarks/>
        public void GetActivityAsync(int activityCode, object userState) {
            if ((this.GetActivityOperationCompleted == null)) {
                this.GetActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActivityOperationCompleted);
            }
            this.InvokeAsync("GetActivity", new object[] {
                        activityCode}, this.GetActivityOperationCompleted, userState);
        }
        
        private void OnGetActivityOperationCompleted(object arg) {
            if ((this.GetActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActivityCompleted(this, new GetActivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFutureCourses", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetFutureCourses() {
            object[] results = this.Invoke("GetFutureCourses", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetFutureCoursesAsync() {
            this.GetFutureCoursesAsync(null);
        }
        
        /// <remarks/>
        public void GetFutureCoursesAsync(object userState) {
            if ((this.GetFutureCoursesOperationCompleted == null)) {
                this.GetFutureCoursesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFutureCoursesOperationCompleted);
            }
            this.InvokeAsync("GetFutureCourses", new object[0], this.GetFutureCoursesOperationCompleted, userState);
        }
        
        private void OnGetFutureCoursesOperationCompleted(object arg) {
            if ((this.GetFutureCoursesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFutureCoursesCompleted(this, new GetFutureCoursesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CourseBL GetCourse(int courseCode) {
            object[] results = this.Invoke("GetCourse", new object[] {
                        courseCode});
            return ((CourseBL)(results[0]));
        }
        
        /// <remarks/>
        public void GetCourseAsync(int courseCode) {
            this.GetCourseAsync(courseCode, null);
        }
        
        /// <remarks/>
        public void GetCourseAsync(int courseCode, object userState) {
            if ((this.GetCourseOperationCompleted == null)) {
                this.GetCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCourseOperationCompleted);
            }
            this.InvokeAsync("GetCourse", new object[] {
                        courseCode}, this.GetCourseOperationCompleted, userState);
        }
        
        private void OnGetCourseOperationCompleted(object arg) {
            if ((this.GetCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCourseCompleted(this, new GetCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddVolunteer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddVolunteer(string phoneNumber, string emergencyPhoneNumber, string fName, string lName, System.DateTime bDate, string userName, string password, string homeAddress, string homeCity, string emailAddress, string id, string policeID, string serveCity, int typeCode) {
            this.Invoke("AddVolunteer", new object[] {
                        phoneNumber,
                        emergencyPhoneNumber,
                        fName,
                        lName,
                        bDate,
                        userName,
                        password,
                        homeAddress,
                        homeCity,
                        emailAddress,
                        id,
                        policeID,
                        serveCity,
                        typeCode});
        }
        
        /// <remarks/>
        public void AddVolunteerAsync(string phoneNumber, string emergencyPhoneNumber, string fName, string lName, System.DateTime bDate, string userName, string password, string homeAddress, string homeCity, string emailAddress, string id, string policeID, string serveCity, int typeCode) {
            this.AddVolunteerAsync(phoneNumber, emergencyPhoneNumber, fName, lName, bDate, userName, password, homeAddress, homeCity, emailAddress, id, policeID, serveCity, typeCode, null);
        }
        
        /// <remarks/>
        public void AddVolunteerAsync(string phoneNumber, string emergencyPhoneNumber, string fName, string lName, System.DateTime bDate, string userName, string password, string homeAddress, string homeCity, string emailAddress, string id, string policeID, string serveCity, int typeCode, object userState) {
            if ((this.AddVolunteerOperationCompleted == null)) {
                this.AddVolunteerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddVolunteerOperationCompleted);
            }
            this.InvokeAsync("AddVolunteer", new object[] {
                        phoneNumber,
                        emergencyPhoneNumber,
                        fName,
                        lName,
                        bDate,
                        userName,
                        password,
                        homeAddress,
                        homeCity,
                        emailAddress,
                        id,
                        policeID,
                        serveCity,
                        typeCode}, this.AddVolunteerOperationCompleted, userState);
        }
        
        private void OnAddVolunteerOperationCompleted(object arg) {
            if ((this.AddVolunteerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddVolunteerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVolunteer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VolunteerBL GetVolunteer(string phoneNumber) {
            object[] results = this.Invoke("GetVolunteer", new object[] {
                        phoneNumber});
            return ((VolunteerBL)(results[0]));
        }
        
        /// <remarks/>
        public void GetVolunteerAsync(string phoneNumber) {
            this.GetVolunteerAsync(phoneNumber, null);
        }
        
        /// <remarks/>
        public void GetVolunteerAsync(string phoneNumber, object userState) {
            if ((this.GetVolunteerOperationCompleted == null)) {
                this.GetVolunteerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVolunteerOperationCompleted);
            }
            this.InvokeAsync("GetVolunteer", new object[] {
                        phoneNumber}, this.GetVolunteerOperationCompleted, userState);
        }
        
        private void OnGetVolunteerOperationCompleted(object arg) {
            if ((this.GetVolunteerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVolunteerCompleted(this, new GetVolunteerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivityBL {
        
        private int activityCodeField;
        
        private string activityNameField;
        
        private System.DateTime activityDateField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime finishTimeField;
        
        private string activityManagerField;
        
        private int typeCodeField;
        
        private string placeField;
        
        private int minNumberOfVolunteerField;
        
        /// <remarks/>
        public int ActivityCode {
            get {
                return this.activityCodeField;
            }
            set {
                this.activityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityName {
            get {
                return this.activityNameField;
            }
            set {
                this.activityNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ActivityDate {
            get {
                return this.activityDateField;
            }
            set {
                this.activityDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FinishTime {
            get {
                return this.finishTimeField;
            }
            set {
                this.finishTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityManager {
            get {
                return this.activityManagerField;
            }
            set {
                this.activityManagerField = value;
            }
        }
        
        /// <remarks/>
        public int TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        public int MinNumberOfVolunteer {
            get {
                return this.minNumberOfVolunteerField;
            }
            set {
                this.minNumberOfVolunteerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VolunteerTypeBL {
        
        private int typeCodeField;
        
        private string typeNameField;
        
        private bool permmisionShiftsField;
        
        private bool permmisionActivityField;
        
        private bool permmisionStockField;
        
        private bool independentField;
        
        private bool permmisionCourseField;
        
        private bool permmisionVolunteerField;
        
        /// <remarks/>
        public int TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        public bool PermmisionShifts {
            get {
                return this.permmisionShiftsField;
            }
            set {
                this.permmisionShiftsField = value;
            }
        }
        
        /// <remarks/>
        public bool PermmisionActivity {
            get {
                return this.permmisionActivityField;
            }
            set {
                this.permmisionActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool PermmisionStock {
            get {
                return this.permmisionStockField;
            }
            set {
                this.permmisionStockField = value;
            }
        }
        
        /// <remarks/>
        public bool Independent {
            get {
                return this.independentField;
            }
            set {
                this.independentField = value;
            }
        }
        
        /// <remarks/>
        public bool PermmisionCourse {
            get {
                return this.permmisionCourseField;
            }
            set {
                this.permmisionCourseField = value;
            }
        }
        
        /// <remarks/>
        public bool PermmisionVolunteer {
            get {
                return this.permmisionVolunteerField;
            }
            set {
                this.permmisionVolunteerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VolunteerBL {
        
        private string phoneNumberField;
        
        private string emergencyNumberField;
        
        private string fNameField;
        
        private string lNameField;
        
        private System.DateTime birthDateField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string homeAddressField;
        
        private string homeCityField;
        
        private string emailAddressField;
        
        private string idField;
        
        private string policeIDField;
        
        private string serveCityField;
        
        private System.DateTime startDateField;
        
        private VolunteerTypeBL typeField;
        
        private bool statusField;
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmergencyNumber {
            get {
                return this.emergencyNumberField;
            }
            set {
                this.emergencyNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FName {
            get {
                return this.fNameField;
            }
            set {
                this.fNameField = value;
            }
        }
        
        /// <remarks/>
        public string LName {
            get {
                return this.lNameField;
            }
            set {
                this.lNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string HomeAddress {
            get {
                return this.homeAddressField;
            }
            set {
                this.homeAddressField = value;
            }
        }
        
        /// <remarks/>
        public string HomeCity {
            get {
                return this.homeCityField;
            }
            set {
                this.homeCityField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string PoliceID {
            get {
                return this.policeIDField;
            }
            set {
                this.policeIDField = value;
            }
        }
        
        /// <remarks/>
        public string ServeCity {
            get {
                return this.serveCityField;
            }
            set {
                this.serveCityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public VolunteerTypeBL Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CourseBL {
        
        private int courseCodeField;
        
        private string courseNameField;
        
        private System.DateTime courseDateField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime finishTimeField;
        
        private string nameOfInstructorField;
        
        private bool isRequeiredField;
        
        private string placeField;
        
        private string descriptionField;
        
        private int validityCodeField;
        
        /// <remarks/>
        public int CourseCode {
            get {
                return this.courseCodeField;
            }
            set {
                this.courseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CourseName {
            get {
                return this.courseNameField;
            }
            set {
                this.courseNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CourseDate {
            get {
                return this.courseDateField;
            }
            set {
                this.courseDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FinishTime {
            get {
                return this.finishTimeField;
            }
            set {
                this.finishTimeField = value;
            }
        }
        
        /// <remarks/>
        public string NameOfInstructor {
            get {
                return this.nameOfInstructorField;
            }
            set {
                this.nameOfInstructorField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRequeired {
            get {
                return this.isRequeiredField;
            }
            set {
                this.isRequeiredField = value;
            }
        }
        
        /// <remarks/>
        public string Place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int ValidityCode {
            get {
                return this.validityCodeField;
            }
            set {
                this.validityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetFutureActivitysCompletedEventHandler(object sender, GetFutureActivitysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFutureActivitysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFutureActivitysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetActivityCompletedEventHandler(object sender, GetActivityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActivityBL Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActivityBL)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetFutureCoursesCompletedEventHandler(object sender, GetFutureCoursesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFutureCoursesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFutureCoursesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetCourseCompletedEventHandler(object sender, GetCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseBL Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseBL)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AddVolunteerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetVolunteerCompletedEventHandler(object sender, GetVolunteerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVolunteerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVolunteerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VolunteerBL Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VolunteerBL)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591